export const Logo = {
  logo: require("../Assets/img/GGI_Logo.png"),
  footer_logo: require("../Assets/img/GGI_Logo.png"),
  twitter_logo: require("../Assets/img/twitter.png"),
  // footer_logo: require("../Assets/img/footer_logo_img.png"),
};

export const FooterImg = {
  footer_img: require("../Assets/img/footer_logo.png"),
  footer_img2: require("../Assets/img/footer_logo2.png"),
  footer_img3: require("../Assets/img/footer_logo3.png"),
	footer_img4: require("../Assets/img/footer_logo_4.png"),
};

export const Img = {
  team_1: require("../Assets/img/Team/1.png"),
	team_2: require("../Assets/img/Team/2.png"),
	team_3: require("../Assets/img/Team/3.png"),
	team_4: require("../Assets/img/Team/4.png"),
	team_5: require("../Assets/img/Team/5.png"),
	team_6: require("../Assets/img/Team/6.png"),
	team_7: require("../Assets/img/Team/7.png"),
	team_8: require("../Assets/img/Team/8.png"),
	team_9: require("../Assets/img/Team/9.png"),
	team_10: require("../Assets/img/Team/10.png"),
	team_11: require("../Assets/img/Team/11.png"),
	team_12: require("../Assets/img/Team/12.png"),
	team_13: require("../Assets/img/Team/13.png"),
	team_14: require("../Assets/img/Team/14.png"),
  team_15: require("../Assets/img/Team/16.png"),
  team_16: require("../Assets/img/Team/17.png"),	  
	bottom_arrow: require("../Assets/img/bottom_arrow.png"),
	home_bottom_arrow: require("../Assets/img/home_dropdown_arrow.png"),
	book_appointment_day: require("../Assets/img/book_appointment_day.png"),
  immigrate_canada_img_1: require("../Assets/img/home_carousel/img_1.png"),
  immigrate_canada_img_2: require("../Assets/img/home_carousel/img_2.png"),
  immigrate_canada_img_3: require("../Assets/img/home_carousel/img_3.png"),
  immigrate_canada_img_4: require("../Assets/img/home_carousel/img_4.png"),
  immigrate_canada_img_5: require("../Assets/img/home_carousel/img_5.png"),
	p1: require("../Assets/img/home_team/1.png"),
	p2: require("../Assets/img/home_team/2.jpg"),
	p3: require("../Assets/img/home_team/3.png"),
	p4: require("../Assets/img/home_team/4.png"),
	p5: require("../Assets/img/home_team/5.png"),
	p6: require("../Assets/img/home_team/6.png"),
	p7: require("../Assets/img/home_team/7.png"),
	p8: require("../Assets/img/home_team/8.png"),	
	girl: require("../Assets/img/image 6.png"),
	study_permit: require("../Assets/img/study_permit.png"),
	unlock_oppertunity: require("../Assets/img/unlock_oppertunity.png"),
	business_visa: require("../Assets/img/visa/business_visa.png"),
	business_visa_1: require("../Assets/img/visa/business_visa.png"),
	start_up_visa: require("../Assets/img/visa/start_up_visa.png"),
	investor_visa: require("../Assets/img/visa/investor_visa.png"),
	intra_company_visa: require("../Assets/img/visa/intra_company_visa.png"),
	self_employed_visa: require("../Assets/img/visa/self_employed_visa.png"),
	card: require("../Assets/img/visa/1.png"),
	temporary_resident_visa: require("../Assets/img/business_visa/temporary_resident_visa.jpg"),
	electronic_travel_authorization: require("../Assets/img/business_visa/Electronic-Travel-Authorization-eTA.jpg"),
	super_visa: require("../Assets/img/business_visa/super_visa.png"),
	business_visitor_visa: require("../Assets/img/business_visa/business_visitor_visa.jpg"),
	parent_and_grandparent_visitor_visa: require("../Assets/img/business_visa/parent_and_grandparent_visitor_visa.png"),
	tourist_visa: require("../Assets/img/business_visa/tourist_visa.jpg"),
	transit_visa: require("../Assets/img/business_visa/transit_visa.png"),
	work_visa: require("../Assets/img/work_visa.png"),
	temporary_work_permit: require("../Assets/img/work_visa/temporary_work_permit.png"),
	international_mobility_program: require("../Assets/img/work_visa/international_mobility_program.png"),
	gobal_talent_stream: require("../Assets/img/work_visa/gobal_talent_stream.png"),
	provincial_nominee_program: require("../Assets/img/work_visa/provincial_nominee_program.png"),
	spousel_work_permit: require("../Assets/img/work_visa/spousel_work_permit.png"),
	post_graduation_work_permit: require("../Assets/img/work_visa/post_graduation_work_permit.png"),
	parents_grandparents_visitor_visa: require("../Assets/img/work_visa/Parent-and-Grandparent-Visitor-Visa.jpg"),
	spousal_work_permit: require("../Assets/img/work_visa/spousel_work_permit.png"),
	bringing_work_permit: require("../Assets/img/work_visa/bringing_work_permit.png"),
	international_experiance_canada: require("../Assets/img/work_visa/international_experiance_canada.png"),
	immigrate: require("../Assets/img/immigrate.png"),
	express_entry: require("../Assets/img/federal_programs/Express-Entry-Canada.jpg"),
	athlentic_immigration_program: require("../Assets/img/federal_programs/athlentic_immigration_program.png"),
	agreefood_immigration_pilot: require("../Assets/img/federal_programs/agreefood_immigration_pilot.png"),
	rural_and_northern_immigration_pilot: require("../Assets/img/federal_programs/Rural-and-Northern-Immigration-Pilot.jpg"),
	caregiver_programs: require("../Assets/img/federal_programs/Caregiver-Programs.jpg"),
	quebec_skilled_worker_program: require("../Assets/img/provincial_programs/QUEBEC-Skilled-worker-program.jpg"),
	ontario_immigrant_nominee_program: require("../Assets/img/provincial_programs/Ontario-Immigrant-Nominee-Program-(OINP).jpg"),
	british_columbia_provincial_nominee_program: require("../Assets/img/provincial_programs/British-Columbia-Provincial-Nominee-Program.jpg"),
	AINP: require("../Assets/img/provincial_programs/AINP.png"),
	SINP: require("../Assets/img/provincial_programs/Saskatchewan-Immigrant-Nominee-Program-(SINP).jpg"),
	MPNP: require("../Assets/img/provincial_programs/MPNP.png"),
	NSNP: require("../Assets/img/provincial_programs/NSNP.png"),
	NBPNP: require("../Assets/img/provincial_programs/NBPNP.png"),
	new_brunswick_provincial_nominee_program: require("../Assets/img/provincial_programs/new_brunswick_provincial_nominee_program.jpg"),
	PEIPN: require("../Assets/img/provincial_programs/PEIPN.png"),
	NLPNP: require("../Assets/img/provincial_programs/Newfoundland-and-Labrador-Provincial.jpg"),
	YNP: require("../Assets/img/provincial_programs/Yukon-Nominee-Program-(YNP).jpg"),
	NTNP: require("../Assets/img/provincial_programs/Northwest-Territories-Nominee-Program.jpg"),
	NNP: require("../Assets/img/provincial_programs/Nunavut-Nominee-Program.jpg"),
	about: require("../Assets/img/about.png"),
	capic: require("../Assets/img/capic.png"),
	CICC: require("../Assets/img/CICC.png"),
	Low_security: require("../Assets/img/Low_security.png"),
	town_of_Whitecourt_Logo: require("../Assets/img/Town_of_Whitecourt_Logo.png"),
	student_visa_banner: require("../Assets/img/breadcrumb/student_visa.jpg"),
	business_visa_banner: require("../Assets/img/breadcrumb/business_visa.jpg"),
	visit_visa_banner: require("../Assets/img/breadcrumb/visit_visa_banner.png"),
	work_visa_banner: require("../Assets/img/breadcrumb/work_visa.jpg"),
	about_us_banner: require("../Assets/img/breadcrumb/banner_about_us.jpg"),
	immigrate_banner: require("../Assets/img/breadcrumb/Immigrate_banner.jpg"),
	blog_banner: require("../Assets/img/breadcrumb/Blogs_banner.jpg"),
	contactus_banner: require("../Assets/img/breadcrumb/contact_us.jpg"),
  contact_canada: require("../Assets/img/contactus/Canada.jpg"),
  contact_india: require("../Assets/img/contactus/India-map.jpg"),
  contact_uae: require("../Assets/img/contactus/UAE.jpg"),
  newsletter_bg: require("../Assets/img/newsletter.png"),
  express_entry: require("../Assets/img/federal_programs/Express-Entry-Canada.jpg"),
  back: require("../Assets/img/BACK.png"),
  testimonial1: require("../Assets/img/test-1.jpeg"),
  testimonial2: require("../Assets/img/test2.jpeg"),
  testimonial3: require("../Assets/img/test3.png"),
  testimonial4: require("../Assets/img/test4.png"),
  testimonial5: require("../Assets/img/test5.jpeg"),
  testimonial6: require("../Assets/img/test6.png"),
  testimonial7: require("../Assets/img/test7.jpeg"),
  testimonial8: require("../Assets/img/test8.png"),
};

export const Icons = {
  arrow_top: require("../Assets/img/top.png"),
  arrow_bottom: require("../Assets/img/bottom.png"),
  useravtar: require("../Assets/img/user_avtar.png"),
  arrow_conact: require("../Assets/img/Hand_Left.png"),
}

export const Blogs_img = {
  blogs_1: require("../Assets/img/blogs/blog_1.jpg"),
  blogs_2: require("../Assets/img/blogs/blog_2.jpg"),
  blogs_3: require("../Assets/img/blogs/blog_3.jpg"),
  blogs_4: require("../Assets/img/blogs/blog_4.jpg"),
  blogs_5: require("../Assets/img/blogs/blog_5.jpg"),
  blogs_6: require("../Assets/img/blogs/blog_6.jpg"),
  blogs_7: require("../Assets/img/blogs/blog_7.jpg"),
  blogs_8: require("../Assets/img/blogs/blog_8.jpg"),
}
