export const Logo = {
  logo: require("../Assets/img/logo_2.png"),
  footer_logo: require("../Assets/img/footer_logo_img.png"),
};

export const FooterImg = {
  footer_img: require("../Assets/img/footer_logo.png"),
  footer_img2: require("../Assets/img/footer_logo2.png"),
  footer_img3: require("../Assets/img/footer_logo3.png"),
	footer_img4: require("../Assets/img/footer_logo_4.png"),
};

export const Img = {
  team_1: require("../Assets/img/Team/1.png"),
	team_2: require("../Assets/img/Team/2.png"),
	team_3: require("../Assets/img/Team/3.png"),
	team_4: require("../Assets/img/Team/4.png"),
	team_5: require("../Assets/img/Team/5.png"),
	team_6: require("../Assets/img/Team/6.png"),
	team_7: require("../Assets/img/Team/7.png"),
	team_8: require("../Assets/img/Team/8.png"),
	team_9: require("../Assets/img/Team/9.png"),
	team_10: require("../Assets/img/Team/10.png"),
	team_11: require("../Assets/img/Team/11.png"),
	team_12: require("../Assets/img/Team/12.png"),
	bottom_arrow: require("../Assets/img/bottom_arrow.png"),
	book_appointment_day: require("../Assets/img/book_appointment_day.png"),
  immigrate_canada_img_1: require("../Assets/img/img-1.png"),
  immigrate_canada_img_2: require("../Assets/img/img-2.png"),
  immigrate_canada_img_3: require("../Assets/img/img-3.png"),
  immigrate_canada_img_4: require("../Assets/img/img-4.png"),
	p1: require("../Assets/img/1.png"),
	p2: require("../Assets/img/2.png"),
	p3: require("../Assets/img/3.png"),
	p4: require("../Assets/img/4.png"),
	p5: require("../Assets/img/5.png"),
	p6: require("../Assets/img/6.png"),
	p7: require("../Assets/img/7.png"),
	girl: require("../Assets/img/image 6.png"),
	study_permit: require("../Assets/img/study_permit.png"),
	unlock_oppertunity: require("../Assets/img/unlock_oppertunity.png"),
	business_visa: require("../Assets/img/business_visa.png"),
	business_visa_1: require("../Assets/img/visa/business_visa.png"),
	start_up_visa: require("../Assets/img/visa/start_up_visa.png"),
	investor_visa: require("../Assets/img/visa/investor_visa.png"),
	intra_company_visa: require("../Assets/img/visa/intra_company_visa.png"),
	self_employed_visa: require("../Assets/img/visa/self_employed_visa.png"),
	card: require("../Assets/img/visa/1.png"),
	temporary_resident_visa: require("../Assets/img/business_visa/temporary_resident_visa.png"),
	electronic_travel_authorization: require("../Assets/img/business_visa/electronic_travel_authorization.png"),
	super_visa: require("../Assets/img/business_visa/super_visa.png"),
	business_visitor_visa: require("../Assets/img/business_visa/business_visitor_visa.png"),
	parent_and_grandparent_visitor_visa: require("../Assets/img/business_visa/parent_and_grandparent_visitor_visa.png"),
	tourist_visa: require("../Assets/img/business_visa/tourist_visa.png"),
	transit_visa: require("../Assets/img/business_visa/transit_visa.png"),
	work_visa: require("../Assets/img/work_visa.png"),
	temporary_work_permit: require("../Assets/img/work_visa/temporary_work_permit.png"),
	international_mobility_program: require("../Assets/img/work_visa/international_mobility_program.png"),
	gobal_talent_stream: require("../Assets/img/work_visa/gobal_talent_stream.png"),
	provincial_nominee_program: require("../Assets/img/work_visa/provincial_nominee_program.png"),
	spousel_work_permit: require("../Assets/img/work_visa/spousel_work_permit.png"),
	post_graduation_work_permit: require("../Assets/img/work_visa/post_graduation_work_permit.png"),
	bringing_work_permit: require("../Assets/img/work_visa/bringing_work_permit.png"),
	international_experiance_canada: require("../Assets/img/work_visa/international_experiance_canada.png"),
	immigrate: require("../Assets/img/immigrate.png"),
	express_entry: require("../Assets/img/federal_programs/express_entry.png"),
	athlentic_immigration_program: require("../Assets/img/federal_programs/athlentic_immigration_program.png"),
	agreefood_immigration_pilot: require("../Assets/img/federal_programs/agreefood_immigration_pilot.png"),
	rural_and_northern_immigration_pilot: require("../Assets/img/federal_programs/rural_and_northern_immigration_pilot.png"),
	caregiver_programs: require("../Assets/img/federal_programs/caregiver_programs.png"),
	quebec_skilled_worker_program: require("../Assets/img/provincial_programs/quebec_skilled_worker_program.png"),
	ontario_immigrant_nominee_program: require("../Assets/img/provincial_programs/ontario_immigrant_nominee_program.png"),
	british_columbia_provincial_nominee_program: require("../Assets/img/provincial_programs/british_columbia_provincial_nominee_program.png"),
	AINP: require("../Assets/img/provincial_programs/AINP.png"),
	SINP: require("../Assets/img/provincial_programs/SINP.png"),
	MPNP: require("../Assets/img/provincial_programs/MPNP.png"),
	NSNP: require("../Assets/img/provincial_programs/NSNP.png"),
	NBPNP: require("../Assets/img/provincial_programs/NBPNP.png"),
	PEIPN: require("../Assets/img/provincial_programs/PEIPN.png"),
	NLPNP: require("../Assets/img/provincial_programs/NLPNP.png"),
	YNP: require("../Assets/img/provincial_programs/YNP.png"),
	NTNP: require("../Assets/img/provincial_programs/NTNP.png"),
	NNP: require("../Assets/img/provincial_programs/NNP.png"),
	about: require("../Assets/img/about.png"),
	capic: require("../Assets/img/capic.png"),
	CICC: require("../Assets/img/CICC.png"),
	Low_security: require("../Assets/img/Low_security.png"),
	student_visa_banner: require("../Assets/img/student_visa_banner.png"),
	business_visa_banner: require("../Assets/img/business_visa_banner.png"),
	visit_visa_banner: require("../Assets/img/visit_visa_banner.png"),
	work_visa_banner: require("../Assets/img/work_visa_banner.png"),
	about_us_banner: require("../Assets/img/about_us_banner.jpg"),
	immigrate_banner: require("../Assets/img/immigrate_banner.jpg"),
  
};

export const Icons = {
  arrow_top: require("../Assets/img/top.png"),
  arrow_bottom: require("../Assets/img/bottom.png"),
}
